environment:
  nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - ps: "npm run dist"  
  - ps: "move dist/bncf-bookdeposit*.exe $env:APPVEYOR_BUILD_FOLDER/"  

artifacts:
  - path: "bncf-bookdeposit*.exe"
    name: bncf-bookdeposit